data = "nomen.db"

[nostr]
relays = ["wss://relay.damus.io"]

# Per NOM-04 spec: Publish indexes to relays
secret = "nsec1..."
publish = true
well-known = true

[server]
bind = "0.0.0.0:8080"
without_explorer = false
without_api = false
without_indexer = false
indexer_delay = 30
confirmations = 3

[rpc]
# Include either cookie or user/password (or none for no RPC auth)
cookie = "path/to/cookie/file"
user = "rpc username"
password = "rpc password"
host = "localhost"
port = 8441
network = "bitcoin"
